=== TrentBartlem/osbutils/trunk/XQTestFramework/testdata/Book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/bookstore" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/bookstore">

    <complexType name="BookType">
    	<sequence>
    		<element name="Title" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="Author" type="string" minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    		<element name="Price" type="double" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="FirstPublished" type="date" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="isbn" type="string" use="required"></attribute>
    </complexType>

    <complexType name="BookListType">
    	<sequence>
    		<element name="Book" type="tns:BookType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <element name="Book" type="tns:BookType"></element>

    <element name="BookList" type="tns:BookListType"></element>
</schema>

=== TrentBartlem/osbutils/trunk/XQTestFramework/testdata/BookList2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:BookList xmlns:tns="http://www.example.org/bookstore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/bookstore Book.xsd ">
  <tns:Book isbn="123-123-123-001-1">
    <tns:Title>The Definitive Guide to OSB</tns:Title>
    <tns:Author>Joe Bloggs</tns:Author>
    <tns:Price>39.99</tns:Price>
    <tns:FirstPublished>2001-01-01</tns:FirstPublished>
  </tns:Book>
  <tns:Book isbn="123-123-123-004-1">
  	<tns:Title>OSB For Dummies</tns:Title>
  	<tns:Author>Jane Doe</tns:Author>
  	<tns:Price>20.99</tns:Price>
  </tns:Book>
  <tns:Book isbn="123-123-123-005-1">
  	<tns:Title>Oracle SOA Suite: OSB</tns:Title>
  	<tns:Author>Larry Ellison</tns:Author>
  	<tns:Price>102.99</tns:Price>
  </tns:Book>
</tns:BookList>

=== TrentBartlem/osbutils/tags/XQTestFramework-v0.2/testdata/BookList1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:BookList xmlns:tns="http://www.example.org/bookstore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/bookstore Book.xsd ">
  <tns:Book isbn="123-123-123-001-1">
    <tns:Title>The Definitive Guide to OSB</tns:Title>
    <tns:Author>Joe Bloggs</tns:Author>
    <tns:Price>39.99</tns:Price>
    <tns:FirstPublished>2001-01-01</tns:FirstPublished>
  </tns:Book>
  <tns:Book isbn="123-123-123-002-1">
  	<tns:Title>Ultimate OSB</tns:Title>
  	<tns:Author>John Doe</tns:Author>
  	<tns:Price>35.99</tns:Price>
  </tns:Book>
  <tns:Book isbn="123-123-123-003-1">
  	<tns:Title>Learn OSB in 7 days</tns:Title>
  	<tns:Author>Joe Bloggs</tns:Author>
  	<tns:Author>John Doe</tns:Author>
  	<tns:Price>47.99</tns:Price>
  </tns:Book>
</tns:BookList>
